import React ,{lazy} from 'react'
import {Redirect} from 'react-router-dom'
import {RouteConfig} from 'react-router-config'

 const routes  :RouteConfig[]=[
    {
        path:'/',
        component:lazy(()=>import('../pages/backstate/backstate-home')),
        exact:true,
        breadcrumb:[
            {title:'旅行报社'},
            {title:'首页'},
        ]
    },
    {
        path:'/backstate/home',
        component:lazy(()=>import('../pages/backstate/backstate-home')),
        breadcrumb:[
            {title:'旅行报社'},
            {title:'首页'},
        ]
    },
    {
        path:'/backstate/personal',
        component:lazy(()=>import('../pages/backstate/backstate-personal')),
        breadcrumb:[
            {title:'旅行报社'},
            {title:'个人中心'},
        ]
    },
    {
        path:'/news/edit',
        component:lazy(()=>import('../pages/news/news-edit')),
        breadcrumb:[
            {title:'新闻'},
            {title:'文章编辑'},
        ]
    },
    {
        path:'/news/check',
        component:lazy(()=>import('../pages/news/news-check')),
        breadcrumb:[
            {title:'新闻'},
            {title:'文章审核'},
        ]
    },
    {
        path:'/news/list',
        component:lazy(()=>import('../pages/news/news-list')),
        breadcrumb:[
            {title:'新闻'},
            {title:'文章列表'},
        ]
    },    {
        path:'/news/draft',
        component:lazy(()=>import('../pages/news/news-draft')),
        breadcrumb:[
            {title:'新闻'},
            {title:'草稿箱'},
        ]
    },
    {
        path:'/ads/edit',
        component:lazy(()=>import('../pages/ads/ads-edit')),
        breadcrumb:[
            {title:'广告'},
            {title:'广告发布'},
        ]
    },
    {
        path:'/ads/check',
        component:lazy(()=>import('../pages/ads/ads-check')),
        breadcrumb:[
            {title:'广告'},
            {title:'广告审核'},
        ]
    },
    {
        path:'/ads/list',
        component:lazy(()=>import('../pages/ads/ads-list')),
        breadcrumb:[
            {title:'广告'},
            {title:'广告列表'},
        ]
    },    
    {
        path:'/ads/effect',
        component:lazy(()=>import('../pages/ads/ads-effect')),
        breadcrumb:[
            {title:'广告'},
            {title:'广告效果数据'},
        ]
    },
    {
        path:'/comments/list',
        component:lazy(()=>import('../pages/comments/comments-list')),
        breadcrumb:[
            {title:'评论'},
            {title:'评论列表'},
        ]
    },
    {
        path:'/comments/check',
        component:lazy(()=>import('../pages/comments/comments-check')),
        breadcrumb:[
            {title:'评论'},
            {title:'评论审核'},
        ]
    },
    {
        path:'/comments/effect',
        component:lazy(()=>import('../pages/comments/comments-effect')),
        breadcrumb:[
            {title:'评论'},
            {title:'评论分析'},
        ]
    },   
    {
        path:'/rightsManager/addRole',
        component:lazy(()=>import('../pages/rightsManager/rightsManager-addRole')),
        breadcrumb:[
            {title:'权限管理'},
            {title:'角色添加'},
        ]
    },
    {
        path:'/rightsManager/addRights',
        component:lazy(()=>import('../pages/rightsManager/rightsManager-addRights')),
        breadcrumb:[
            {title:'权限管理'},
            {title:'权限添加'},
        ]
    },  
    {
        path:'/rightsManager/edit/addRights',
        component:lazy(()=>import('../pages/rightsManager/rightsManager-addRight-page')),
        breadcrumb:[
            {title:'权限管理'},
            {title:'权限添加',to:'/rightsManager/addRights'},
            {title:'选择权限'},
        ]
    },  
    {
        path:'/error',
        component:lazy(()=>import('../pages/common/error')),
    },
    {
        path:'/islogin',
        component:lazy(()=>import('../pages/common/login')),
    },
    {
        path:'/forbidden',
        component:lazy(()=>import('../pages/common/forbidden')),
    },
    {
        path:'/no-match',
        component:lazy(()=>import('../pages/common/no-match')),
    },
    {
        path:'**',
        render:()=><Redirect to="/no-match"/>
    },
]


export default routes;